name: Update stats

on:
  schedule:
    # Runs at 12am UTC
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: waka_2b9a40ff-1b00-498f-9305-5f48d7d76277
          SHOW_TITLE: true
          HEAD_FLAG: true
        
